apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cfzu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cfzu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cfzu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cfzu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cfzu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nsve-tenant/rhtap-demo-app/hacbs-test-project-cfzu@sha256:97a173f15589a5f22778287bf4b49606eda4680c87c5228e70b53278b4a8120a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
